# Origin gridfile info
grids_dir: null
grid_name: null

# Data to regrid info
data_dir: null
data_name: null

# Target grid info
target_grid_dir: null
target_grid_name: null

methods: 
  - nn
  - con
  - bil